sonar.sources=internal,public,scripts

sonar.organization=test-gogs 
sonar.projectKey=test-gogs_gogs 

sonar.qualitygate.wait=true

# sonar.organization=gogs
# sonar.projectKey=finkord_gogs
# sonar.host.url=https://sonarcloud.io