pipeline {
    agent any
    
    environment {
        GO_VERSION = '1.24.0'
    }
    
    tools {
        go "${GO_VERSION}" 
    }

    triggers {
        pollSCM('H/2 * * * *')
    }
    
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    stages {
        // stage('Checkout') {
        //     steps {
        //         git credentialsId: 'f109eef9-e07b-413c-b686-ea287ecc170d',
        //             url: 'https://github.com/finkord/gogs',
        //             branch: 'main'
        //     }
        // }
        
        stage('Validate & Generate Code') {
            steps {
                sh'go version'
                sh"go mod tidy"
                sh"sudo apt-get update && sudo apt-get install -y build-essential"
                sh"go install golang.org/x/tools/cmd/goimports@latest"
                sh"""
                   export PATH=$PATH:\$(go env GOPATH)/bin
                   CGO_ENABLED=1 go generate ./... """
            }
        }

        stage('Lint') {
            steps {
                script {
                    sh """
                        echo "Installing golangci-lint..."
                        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b \$(go env GOPATH)/bin v2.1.6
                        export PATH=$PATH:\$(go env GOPATH)/bin
                        golangci-lint run --timeout=30m
                    """
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    try {
                        sh 'go test -cover -race -coverprofile=coverage.out -covermode=atomic ./...'
                    } catch (err) {
                        echo "Tests failed: ${err}"
                        currentBuild.result = 'FAILURE'
                    } finally {
                        if (fileExists('report.xml')) {
                            junit 'report.xml'
                        }
                    }

                }
            }
        }
        
        stage('Build') {
            steps {
                sh 'go build -v .'
            }
        }
        
        stage('Archive Build') {
            steps {
                script {
                    def buildArtifactsDir = "artifacts/build_${BUILD_NUMBER}"
                    sh """
                    mkdir -p artifacts
                    mkdir -p ${buildArtifactsDir}/log
                    mkdir -p ${buildArtifactsDir}/coverages
                    
                    cp ./gogs ${buildArtifactsDir}/
                    cp -r ./scripts ${buildArtifactsDir}/scripts
                    go tool cover -html=coverage.out -o coverage.html
                    cp ./coverage*.out ${buildArtifactsDir}/coverages/
                    """
                    publishHTML([reportDir: '.', reportFiles: 'coverage.html', reportName: 'Go Coverage'])
                    archiveArtifacts artifacts: "${buildArtifactsDir}/**", fingerprint: true
                }
            }
        }
    }
    
    post {
        // always {
        //     cleanWs()
        // }
        success {
            echo 'Gogs build succeeded!'
        }
        failure {
            echo 'Gogs build failed!'
        }
    }
}