pipeline {
    // agent any
    agent {label'amazon-linux-with-docker'}

    environment {
        // Golang
        GO_VERSION      = '1.24.0'
        // ECR
        ECR_NAMESPACE   = 'gogs'
        ECR_REPO_NAME   = 'test'
        ECR_URI         = "${env.ECR_URI}"
        ECR_REGION      = "${env.ECR_REGION}"
        FULL_IMAGE_NAME = "${ECR_URI}/${ECR_NAMESPACE}/${ECR_REPO_NAME}"
    }
    
    tools {
        go "${GO_VERSION}" 
    }
    
    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '20'))
    }

    stages {

        stage('Notify') {
            steps {
                discordSend(
                    webhookURL: env.DISCORD_WEBHOOK,
                    title: env.JOB_NAME,
                    link: env.BUILD_URL,
                    description: "Pipeline Started: build ${env.BUILD_NUMBER}",
                    result: 'ABORTED',
                )
            }
        }

        // stage('Validate & Generate Code') {
        //     steps {
        //         sh"go mod tidy"
        //         sh"go install golang.org/x/tools/cmd/goimports@latest"
        //         sh"""
        //           export PATH=$PATH:\$(go env GOPATH)/bin
        //           CGO_ENABLED=1 go generate ./... 
        //         """
        //     }
        // }

        // stage('Lint') {
        //     steps {
        //         sh '''
        //         WORKDIR="$(pwd)"
        //         docker run --rm \
        //             -v "$WORKDIR":/app \
        //             -w /app \
        //             golangci/golangci-lint:v2.1.6 \
        //             golangci-lint run --timeout=30m || true
        //         '''
        //     }
        // }

        stage('SonarQube Analysis') {
            steps {
                script {
                    scannerHome = tool 'SonarQube Scanner'
                    withSonarQubeEnv('SonarQube Cloud') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Quality Checks') {
            parallel {
                stage('Coverage Test') {
                    steps {
                        sh 'go test -cover -race -coverprofile=coverage.out -covermode=atomic ./...'
                    }
                }
                
                stage('Snyk Security Test') {
                    steps {
                        script {
                            try {
                                snykSecurity(
                                    snykInstallation: 'snyk@latest',
                                    snykTokenId: 'snyk_api',
                                    additionalArguments: '--all-projects',
                                    // failOnIssues: false
                                )
                            } catch (err) {
                                echo "Snyk failed: ${err}"
                                discordSend(
                                    webhookURL: env.DISCORD_WEBHOOK,
                                    title: env.JOB_NAME,
                                    link: env.BUILD_URL,
                                    description: "Snyk Test Failed: build ${env.BUILD_NUMBER}",
                                    result: 'UNSTABLE'
                                )
                            }
                        }
                    }
                }
            }
        }

        stage('Prepare Variables') {
            steps {
                script {
                    def branch    = env.GIT_BRANCH?.replaceAll(/^origin\//, '')?.replaceAll('/', '-') ?: 'unknown'
                    def commit    = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
                    def timestamp = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
                    env.IMAGE_TAG = "${branch}-${commit}-${timestamp}"
                    echo "Assigned IMAGE_TAG = ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Build Docker Image & Push to AWS ECR') {
            steps {
                withAWS(region: "${env.ECR_REGION}") {
                    sh """
                    aws ecr get-login-password --region ${env.ECR_REGION} | \
                    docker login --username AWS --password-stdin ${env.ECR_URI}
                    """
                }
                script {
                    def gogsImage = docker.build("${env.FULL_IMAGE_NAME}:${env.IMAGE_TAG}")
                    gogsImage.push(env.IMAGE_TAG)
                    gogsImage.push('latest')

                    sh """
                    docker rmi ${env.FULL_IMAGE_NAME}:${env.IMAGE_TAG} || true
                    docker rmi ${env.FULL_IMAGE_NAME}:latest || true
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            discordSend(
                webhookURL: env.DISCORD_WEBHOOK,
                title: env.JOB_NAME,
                link: env.BUILD_URL,
                description: "Pipeline Success: build ${env.BUILD_NUMBER}",
                result: 'SUCCESS',
                showChangeset: true,
            )
        }
        failure {
            discordSend(
                webhookURL: env.DISCORD_WEBHOOK,
                title: env.JOB_NAME,
                link: env.BUILD_URL,
                description: "Pipeline Failed: build ${env.BUILD_NUMBER}",
                result: 'FAILURE',
                showChangeset: true,
            )
        }
        aborted {
            discordSend(
                webhookURL: env.DISCORD_WEBHOOK,
                title: env.JOB_NAME,
                link: env.BUILD_URL,
                description: "Pipeline Aborted: build ${env.BUILD_NUMBER}",
                result: 'ABORTED',
            )
        }
    }
}
